user_app/urls.py
from django.conf.urls import url
from user_app import views

app_name = 'user_app'

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='login'),

]

user_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from user_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^user_app/',include('user_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout,name='logout'),
]

user_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    #table
    user = models.OneToOneField(User)

    #attributes
    portofolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

user_app/forms.py
from django import forms
from django.contrib.auth.models import User
from user_app.models import UserProfileInfo


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portofolio_site', 'profile_pic')

user_app/views.py
from django.shortcuts import render
from user_app.forms import UserForm, UserProfileInfoForm

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, 'user_app/index.html')


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()


    return render(request, 'user_app/registration.html', {'user_form': user_form,
                                                          'profile_form': profile_form,
                                                          'registered': registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your Account is not active")
        else:
            print("User tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'user_app/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/user_app/index.html
{% extends "user_app/user.html" %}

{% block body_block %}
  <div class="container">
  <div class="jumbotron">
    <h1>Django Level Five</h1>
    {% if user.is_authenticated %}
        <h2>Welcome {{ user.username }}!</h2>
    {% else %}
        <h2>Welcome to the site!</h2>
    {% endif %}
  </div>
  </div>
{% endblock %}

templates/user_app/login.html
{% extends 'user_app/user.html' %}
{% block body_block %}
    <h1>Please Login</h1>
    <form method="POST" action="{% url 'user_app:login' %}">
      {% csrf_token %}
         <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">
    </form>
  {% endblock %}

templates/user_app/registration.html
{% extends "user_app/user.html" %}

{% block body_block %}
  {% if registered %}
   <h1>Thank you for signing up </h1>
  {% else %}
    <h1>Register here</h1>
    <h3>Just fill out the form</h3>

    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
  {% endif %}
{% endblock %}

templates/user_app/user.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>USER PAGE & INDEX PAGE</title>
  </head>
  <body>
   {% if user.is_authenticated %}
   <ul>
      <li><a href="{% url 'logout'%}">LOG OUT </a></li>
     {% else %}
      <li><a href="{% url 'user_app:login' %}"> LOGIN </a></li>
      <li><a href="{% url 'user_app:register' %}"> Register </a></li>

   {% endif %}
  </ul>
  {% block body_block %}
  {% endblock %}
  </body>

</html>